- 2007-01-01:
    CropCalendar:
        crop_name: wheat
        variety_name: winter wheat
        crop_start_date: 2007-01-01
        crop_start_type: emergence
        crop_end_date: 2007-09-01
        crop_end_type: earliest
        max_duration: 365
    StateEvents:
    TimedEvents:

