name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
    test:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest]
          python-version: ['3.11']
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pip uninstall -y --quiet pcse
          git clone https://github.com/ajwdewit/pcse.git /tmp/pcse
          cd /tmp/pcse && git switch develop_WOFOST_v8_1 && git apply --ignore-space-change --ignore-whitespace ${GITHUB_WORKSPACE}/notebooks/nitrogen-winterwheat/pcse-lintul3.patch && pip install --quiet -e . && cd ${GITHUB_WORKSPACE}
          pip install stable_baselines3==2.1.0 sb3-contrib gymnasium lib_programname tensorboard scipy tqdm pandas numpy
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          export PYTHONPATH="${PYTHONPATH}:${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE}/pcse_gym"
          pytest tests/test* -W ignore::DeprecationWarning