name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
    test:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest]
          python-version: ['3.9']
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pip uninstall -y --quiet pcse
          git clone https://github.com/ajwdewit/pcse.git /tmp/pcse
          cd /tmp/pcse && git switch develop_wofost81 && git reset --hard 67a3d0c3a46280bddcf7617de3b27c82e5cb0a40 && pip install --quiet -e . && cd ${GITHUB_WORKSPACE}
          pip install dotmap
          pip install stable_baselines3 sb3-contrib
          pip install gymnasium==0.28.1 lib_programname tensorboard scipy tqdm pandas numpy
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          export PYTHONPATH="${PYTHONPATH}:${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE}/pcse_gym"
          pytest tests/test* -W ignore::DeprecationWarning