name: Test
on:
 push:
    branches: [ "develop" ]
 pull_request:
    branches: [ "develop" ]
jobs:
    test:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest]
          python-version: ['3.11']
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pip uninstall -y --quiet pcse
          cd ..
          rm -fr pcse
          git clone https://github.com/ajwdewit/pcse.git
          cd pcse && git switch develop_WOFOST_v8_1 && git apply --ignore-space-change --ignore-whitespace ../PCSE-Gym/_notebooks_old/nitrogen-winterwheat/pcse-lintul3.patch
          pip install --quiet -e . && cd .. && cd PCSE-Gym
          pip install stable_baselines3 sb3-contrib gymnasium lib_programname tensorboard scipy tqdm pandas
          pip install numpy==1.24.3
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          echo "$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/pcse_gym" >> $GITHUB_ENV
          echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "PYTHONPATH=$GITHUB_WORKSPACE/pcse_gym" >> $GITHUB_ENV
          pytest tests/test* -W ignore::DeprecationWarning
